TITLE_1: 4302305
TITLE_2: Mecânica Clássica I
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |

GITHUB_LINK: https://github.com/Academic-Codex/IF4302305-Mecanica-Classica-I

HERO_FILE: mecanica-classica-I.png
